version: '3.9'

services:
  silverback-web:
    build: .
    container_name: silverback-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    command: ["gunicorn", "app:app", "--bind", "0.0.0.0:5000", "--workers", "4", "--timeout", "120"]

  silverback-bot:
    build: .
    container_name: silverback-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./silverback_prod.db:/app/silverback_prod.db
      - ./silverback.log:/app/silverback.log
